import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

const HomePage: React.FC =(): JSX.Element=> {
  return (
    <>
      <Head>
        <title>Ekip Kalir's Portfolio Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.homepage}>
        <h5 className={styles.home5}>Welcome to my personal page.</h5>
        <p className={styles.homep}>
          This is my personal portfolio page. Having a system engineer background,
          I am coming from the jungle of computer nerds compared to computer science coders.
          I love to learn new things and improve my skills.
        </p>
        <p className=""><small className={styles.homesmall}>Last updated 3 mins ago</small></p>
      </div>
    </>
  )
}

export default HomePage